package cn.gdmcmc.www.demo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.gdmcmc.www.demo.dao.Record;
import cn.gdmcmc.www.demo.dao.RecordItem;

import cn.gdmcmc.www.demo.dao.RecordDao;
import cn.gdmcmc.www.demo.dao.RecordItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordDaoConfig;
    private final DaoConfig recordItemDaoConfig;

    private final RecordDao recordDao;
    private final RecordItemDao recordItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        recordItemDaoConfig = daoConfigMap.get(RecordItemDao.class).clone();
        recordItemDaoConfig.initIdentityScope(type);

        recordDao = new RecordDao(recordDaoConfig, this);
        recordItemDao = new RecordItemDao(recordItemDaoConfig, this);

        registerDao(Record.class, recordDao);
        registerDao(RecordItem.class, recordItemDao);
    }
    
    public void clear() {
        recordDaoConfig.clearIdentityScope();
        recordItemDaoConfig.clearIdentityScope();
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

    public RecordItemDao getRecordItemDao() {
        return recordItemDao;
    }

}
